services:
  yuge_subscriber:
    build:
      context: .
      dockerfile: build/Dockerfile.subscriber
    restart: always
    image: yuge_subscriber:${YUGE_SUBSCRIBER_VERSION}
    container_name: yuge_subscriber
    environment:
      - JETSTREAM_WS_URL=${JETSTREAM_WS_URL}
      - FEED_EDITOR_ENDPOINT=${FEED_EDITOR_ENDPOINT}
      - SUBSCRIBER_LOG_LEVEL=${LOG_LEVEL}
      - CF_ACCESS_CLIENT_ID=${CF_ACCESS_CLIENT_ID}
      - CF_ACCESS_CLIENT_SECRET=${CF_ACCESS_CLIENT_SECRET}
    ports:
      - "8082:8082"
      - "9102:9102"
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
